define("core/panel/Mask",["jQuery","core/panel/Panel"],function(c){var f=c("jQuery");c=c("core/panel/Panel");var g=K.mix,i=K.extend,j=K.CustEvent,e=i(function(a){this._initMask(a)},c);g(e.prototype,{_initMask:function(a){this.MASK_CLASS="panel-mask";this.resizeInterval=this.scrollInterval=50;this.topOffset=this.leftOffset=200;this.rightOffset=0;this.bottomOffset=200;if(a){if(!("useBlurClose"in a))a.useBlurClose=false}else a={useBlurClose:false};g(this,a);e.$super.call(this,a);this._iframe&&this._coverIframe();
j.createEvents(this,"activate");this._addMaskEvent();a=this._canbeFixed()?"fixed":"absolute";this.addClass(this.MASK_CLASS);this.setStyle("position",a);this.addClass(this.className);var b=this;this.on("aftershow",function(){b.adaptBounds()})},_addMaskEvent:function(){var a=this;if(!this._canbeFixed()){f(window).bind("scroll",function(){clearTimeout(a._scrollTimer);a._scrollTimer=setTimeout(function(){clearTimeout(a._scrollTimer);a.adaptBounds()},a.scrollInterval)});f(window).bind("resize",function(){clearTimeout(a._resizeTimer);
a._resizeTimer=setTimeout(function(){clearTimeout(a._resizeTimer);a.adaptBounds()},a.resizeInterval)})}var b=this;this.getPanel().mousedown(function(){b.fire("activate")})},adaptBounds:function(){var a=this.getPanel();if(a){if("fixed"!=a.css("position").toLowerCase()){var b=this.getWinRect();a={width:a.width(),height:a.height()};var d=y=w=h=0;d=b.scrollLeft-this.leftOffset<=0?0:b.scrollLeft-this.leftOffset;y=b.scrollTop-this.topOffset<=0?0:b.scrollTop-this.topOffset;w=this.rightOffset;h=this.bottomOffset;
w+=b.width;h+=b.height;if(a.width>w)w=null;if(a.height>h)h=null;this.setRect({left:d,top:y,width:w,height:h})}else{this.setStyle("width","100%");this.setStyle("height","100%");this.setStyle("left","0");this.setStyle("top","0")}return this}},follow:function(a){if(a){var b=this;this.flollowPanel=a;a.on("aftershow",function(){b.show();var d=parseInt(a.getZIndex(),10);b.getPanel().css("z-index",d-1)});a.on("afterhide",function(){b.hide()});a.on("afterdispose",function(){b.dispose()});return this}},_coverIframe:function(){this.getPanel().find(".panel-content").css("position",
"absolute").css("z-index","1").css("width","100%").css("height","100%")}});return e});

define("core/panel/Panel",["jQuery"],function(i){function g(a){this.PANEL_CLASS="panel";this.IFRAME_CLASS="panel-iframe";this.INNER_CLASS="panel-content";this.id=this.PANEL_CLASS+"_"+new Date*1+"_"+K.uniqueId();this.atCenter=true;this.delay=300;this.useBlurClose=false;f(this,a);this.useIframe="useIframe"in this?this.useIframe:this._needIframe();this.top=this.top||0;this.left=this.left||0;j.createEvents(this,"beforeinit,afterinit,beforeshow,aftershow,beforehide,afterhide,beforedispose,afterdispose");
this.fire("beforeinit");this._init();this.fire("afterinit")}var c=i("jQuery"),f=K.mix,e=K.Browser,j=K.CustEvent,k=9E4;f(g.prototype,{_init:function(){this._createPanelBox();this._bindPanelEvents();this.visible=this.isPanelShow()},_createPanelBox:function(){this._panel=c('<div class="'+this.PANEL_CLASS+'" id="'+this.id+'"></div>');this.useIframe&&this._createIframe();this._content=c('<div class="'+this.INNER_CLASS+'"></div>');this._panel.append(this._content);this._panel.appendTo(c("body"));var a=
{left:this.left,top:this.top};if(!isNaN(this.width))a.width=this.width;if(!isNaN(this.height))a.height=this.height;this.setRect(a);this._panel.hide();this.noBlurList=[this._panel[0]]},_createIframe:function(){this._iframe=c('<iframe class="'+this.IFRAME_CLASS+'" frameborder="0" src="about:blank"></iframe>');this._iframe.css("width","100%").css("height","100%");this._panel.append(this._iframe)},_needIframe:function(){return parseInt(e.ie,10)===6&&(document.getElementsByTagName("select").length||document.getElementsByTagName("object").length)},
_canbeFixed:function(){return!e.ie||e.ie&&e.ie>6},_bindPanelEvents:function(){this.useBlurClose&&c(document).bind("mousedown",{ins:this},this._blurListener)},_blurListener:function(a){var b=a.target;a=a.data.ins;a.visible&&a.isTriggerBlur(b)&&a.hide()},_clearPanelEvents:function(){this.useBlurClose&&c(document).unbind("mousedown",this._blurListener);this._panel.unbind()},isTriggerBlur:function(a){var b=this._panel[0],d=false;K.forEach(this.noBlurList,function(h){if(h==a||c.contains(h,a))d=true});
return c.contains(b,a)||d?false:true},show:function(a,b){if(arguments.length==1&&!c.isPlainObject(a)){b=a;a={top:0,left:0}}if(b){b=c(b);var d=b.offset();a.top+=d.top;a.left+=d.left}a&&this.setRect(a);this.fire("beforeshow");this._panel.css("z-index",k++);this._panel.show();this.atCenter&&this.center();this.visible=true;this.fire("aftershow");return this},hide:function(){this.fire("beforehide");this._panel.hide();this._clearTimer();this.visible=false;this.fire("afterhide");return this},delayShow:function(){var a=
this,b=arguments;this._clearTimer();this._delayTimer=setTimeout(function(){a._delayTimer=null;a.show(b)},this.delay);return this},_clearTimer:function(){this._delayTimer&&clearTimeout(this._delayTimer)},setRect:function(a){var b=a.width,d=a.height;this._panel.offset(a);typeof b!="undefined"&&this._panel.width(b);typeof d!="undefined"&&this._panel.height(d);return this},setSize:function(a,b){a&&this._panel.width(a);b&&this._panel.height(b);return this},setXY:function(a,b){this._panel.offset({top:b,
left:a});return this},center:function(){var a=this.getRect(),b=this.getWinRect(),d=a.height;a=parseInt((b.width-a.width)/2);d=parseInt((b.height-d)/2);if(a<0)a=0;if(d<0)d=0;if("fixed"!=this._panel.css("position")){a+=b.scrollLeft;d+=b.scrollTop;if(a<=b.scrollLeft)a=b.scrollLeft;if(d<=b.scrollTop)d=b.scrollTop}this.setXY(a,d);return this},contains:function(a){return c.contains(this._panel,a)},getRect:function(){var a=this._panel.offset();f(a,{width:this._panel.width(),height:this._panel.height()});
return a},appendToPanel:function(a){this._panel.append(a);return this},appendToContent:function(a){this._content.append(a);return this},getPanel:function(){return this._panel},getIframe:function(){return this._iframe},getZIndex:function(){return this._panel[0].style.zIndex},setFullscreen:function(){this.setRect({top:0,left:0,height:c(document).height(),width:c(document).width()});return this},addClass:function(a){this._panel.addClass(a);return this},setStyle:function(a,b){this._panel.css(a,b);return this},
addNoBlurList:function(a){if(a){if(a.jquery)a=a[0];a&&this.noBlurList.push(a)}},isPanelShow:function(){return this._panel.css("visibility")!="hidden"&&this._panel.css("display")!="none"},getWinRect:function(){return{scrollLeft:c(window).scrollLeft(),scrollTop:c(window).scrollTop(),width:c(window).width(),height:c(window).height()}},dispose:function(){this.fire("beforedispose");this._clearPanelEvents();this._iframe&&this._iframe.remove();this._panel&&this._panel.remove();this.fire("afterdispose")}});
return g});

define("core/panel/Dialog",["jQuery","core/panel/Panel","core/panel/Mask"],function(d){var c=d("jQuery"),g=d("core/panel/Panel"),h=d("core/panel/Mask"),f=K.mix;d=K.extend;var b=d(function(a){this._initDialog(a)},g);f(b.prototype,{_initDialog:function(a){this.useFoot=this.useHead=this.useMask=true;this.foot=this.content=this.title="";this.className="kxDialog";this.clickMaskClose=false;f(this,a);b.$super.call(this,a);this.addClass(this.className);this._createDialog();this.useMask&&this._createMask();
this._bindEvents();this.title&&this.setTitle(this.title);this.useHead||this._hd.hide();this.content&&this.setContent(this.content);this.foot&&this.setFooter(this.foot);this.useFoot||this._ft.hide();this.layout();b.add(this)},_createDialog:function(){this._hd=c('<div class="hd"/>');this._bd=c('<div class="bd"/>');this._ft=c('<div class="ft"/>');this.appendToContent(this._hd);this.appendToContent(this._bd);this.appendToContent(this._ft);this._sd=c('<div class="sd"/>');this.appendToPanel(this._sd);this._close=
c('<div class="kxDialogClose">\u00d7</div>');this.appendToPanel(this._close)},_createMask:function(){var a={};this.maskOption&&K.mix(a,this.maskOption);this._mask=new h(a);this._mask.follow(this);if(this.clickMaskClose){var e=this;this._mask.on("activate",function(){e.hide()})}this.embedMask&&this.getPanel().appendTo(this._mask.getPanel())},_bindEvents:function(){var a=this;this._close.click(function(){a.hide()});K.Browser.ie==6&&this.on("aftershow",function(){})},setSize:function(a,e,i){b.$super.prototype.setSize.call(this,
a,e);this.layout(!!i);return this},setFullscreen:function(){b.$super.prototype.setFullscreen.call(this);this.layout();return this},setTitle:function(a){this.title=a;this._hd.html("<h3>"+a+"</h3>");return this},setContent:function(a){if(c.type(a)=="string")this._bd.html(a);else{this._bd.empty();this._bd.append(c(a))}},setFooter:function(a){this.foot=a;this._ft.html(a);return this},layout:function(a){this.atCenter&&a!==false&&this.center()},getMask:function(){return this._mask},getClose:function(){return this._close},
dispose:function(){b.$super.prototype.dispose.call(this);this._mask&&this._mask.dispose();b.remove(this)}});K.mix(b,{instances:[],add:function(a){K.indexOf(this.instances,a)===-1&&this.instances.push(a)},remove:function(a){a=K.indexOf(this.instances,a);a>-1&&this.instances.splice(a,1)},disposeAll:function(){for(var a=this.instances.length;a>=0;a--)this.instances[a].dispose()}});return b});

define("core/panel/Window",["jQuery","core/panel/Dialog"],function(g){var m=g("jQuery"),j=g("core/panel/Dialog");g=K.mix;var n=K.extend,d=n(function(a){this._initWindow(a)},j);g(d.prototype,{_initWindow:function(a){if(a.compatible&&a.height&&a.title!==false)a.height+=10;if(a.compatible&&a.width)a.width-=16;d.$super.call(this,a);this.setUrl(this.url)},open:function(a){this.setUrl(a);this.show();return this},setSize:function(a,b,c){if(this.compatible&&b&&this.title!==false)b+=10;if(this.compatible&&
a)a-=16;var e=b;if(this.title!==false)e-=this._hd.outerHeight();this.getPanel().find("iframe").height(e);d.$super.prototype.setSize.call(this,a,b,c);return this},show:function(){d.$super.prototype.show.apply(this,arguments);if(this.compatible&&this.title===false){this._hd.hide();this._close.hide()}},setUrl:function(a){if(this.url=a||this.url){this.getPanel().find("iframe").remove();a=this.height;if(this.title!==false)a-=this._hd.outerHeight();this.url+="#window_id="+this.id+"#";a=m('<iframe src="#" width="100%" frameborder="no" scrolling="no"/>').height(a);
this.setContent(a);this._bindClose(a);a.attr("src",this.url)}return this},dispose:function(){this.getPanel().find("iframe").remove();d.$super.prototype.dispose.call(this)},_bindClose:function(a){var b=this,c=function(){parent.KXWindow.getOwner(a.get(0).contentWindow).hide()};a.bind("load",function(){try{var e=a.get(0).contentWindow;e._window_panel_id_=b.id;e.close=c}catch(f){}var k=setInterval(function(){var i=a.get(0).contentWindow;try{if(i.close!=c)i.close=c;else clearInterval(k)}catch(h){}},300)})}});
g(d,{open:function(a,b,c,e,f,k,i){var h=new d({url:a,width:b,height:c,title:e,compatible:i,className:k||"kxDialog"});if(f)for(var l in f)h.on(l,function(o){return function(){f[o].apply(h,arguments)}}(l));h.show();return h},openSingle:function(){for(var a=j.instances,b=0,c=a.length;b<c;b++)a[b].hide();return d.open.apply(d,arguments)},getOwner:function(a){var b=/^.+#window_id=(\w+).*$/,c=a.location.href;a=a._window_panel_id_?a._window_panel_id_:c.replace(b,"$1");b=j.instances;c=0;for(var e=b.length;c<
e;c++){var f=b[c];if(f.id==a)return f}}});return d});

define("core/panel/MessageBox",["jQuery","core/panel/Dialog"],function(j){var h=j("jQuery");j=j("core/panel/Dialog");var l=K.mix,m=K.extend,f=m(function(a){this._initMBox(a)},j);l(f.prototype,{_initMBox:function(a){this.boxClass="mbox-t1";this.buttons=null;f.$super.call(this,a);this._createContent()},_createContent:function(){var a=h('<div class="'+this.boxClass+'"/>'),c=h('<div class="ct"/>'),b=h('<div class="kxDialogBtnWrap"/>');this._act=h('<div class="kxDialogBtn clearfix"/>');a.append(c);a.append(b);
b.append(this._act);this.setContent(a);this._bd=c;this.setContent(this.content);this.setButton(this.buttons)},setButton:function(a){var c=this;this._act.empty();var b=[];if(a)if(K.isString(a)){a=a.split("|");for(var e=0,i=a.length;e<i;e++)b.push({label:a[e],className:"kxbtn_s"})}else b=a;else b=[{label:"\u786e\u5b9a",className:"kxbtn_s"}];if(!this.onClick)this.onClick=function(d){d.hide()};K.forEach(b,function(d){var g=h('<span class="kxbtn '+d.className+'"><button class="normal"><em><span><b><i>'+
d.label+"</i></b></span></em></button></span>");g.appendTo(c._act);g.click(function(){c.onClick(c,d.label)})});return this}});l(f,{alert:function(a,c,b,e,i,d,g){a=new f({content:a,width:b||350,height:e,title:c,buttons:i,onClick:d,className:g||"kxDialogAlert"});a.show();return a},confirm:function(a,c,b,e,i,d,g){return f.alert(a,e,i||350,d,[{label:"\u786e\u5b9a",className:"kxbtn_s"},{label:"\u53d6\u6d88",className:"kxbtn_gray_s"}],function(k,n){if(n=="\u786e\u5b9a"&&c)c(k);else b&&b(k);k.hide()},g)}});
return f});

define("core/panel/AsyncDialog",["jQuery","core/async/Request","core/panel/Dialog"],function(g){var k=g("jQuery"),l=g("core/async/Request");g=g("core/panel/Dialog");var d=function(a){this.pb=new K.Pubsub;d.$super.call(this,a)};K.extend(d,g);K.mix(d,{instances:{},generateID:function(){return K.uniqueId("__dialog__")},getInstance:function(a){return d.instances[a]},destroy:function(a){a in d.instances&&delete d.instances[a]},load:function(a,c,b){if(a){var e="GET",f={},h=350,i=100,j=d.loadingContent,
m=b&&"autoShow"in b?b.autoShow:true;if(c)if(k.isPlainObject(c)){e=c.method||e;h=c.loadingWidth||h;i=c.loadingHeight||i;j=c.loadingContent||j;f=c.data||f}else{c=k(c);e=c.attr("data-ajax")=="dialog-post"?"POST":e;h=c.attr("data-loading-width")||h;i=c.attr("data-loading-height")||i;j=c.attr("data-loading-content")||j;if(c.attr("data-data"))f=k.parseJSON(c.attr("data-data"))}a=(new l).setMethod(e).setData(f).setURI(a);b=(new d(K.mix({content:j},b))).setAsyncRequest(a).setSize(h,i);m&&b.show();return b}},
loadingContent:'<div style="padding-top: 30px; background:#fff; height: 30px; text-align: center;"><img src="http://'+K.Env.IMG_HOST+'/i/homenew/loading.gif"></div>',handlerFactory:function(a,c,b){a=K.create(a);K.mix(a,{container:'div[data-dialog-id="'+c+'"]',metaData:b,getDialog:function(){return d.getInstance(c)}});return a}});K.mix(d.prototype,{destroy:function(){this.dispose();d.destroy(this._dialogId)},setAsyncRequest:function(a){this._async_request=a;a.setHandler(K.bind(function(c){if(!(this._async_request!=
a||this.autoShow!==false&&!this.visible)){this._async_request=null;var b=c.content.dialog,e=this._dialogId;if(!e){e=this._dialogId=d.generateID();d.instances[this._dialogId]=this}b.title&&this.setTitle(b.title);if(b.body)this.getPanel().find("div[data-dialog-id]").length?this.getPanel().find("div[data-dialog-id]").html(b.body):this.setContent('<div data-dialog-id="'+e+'">'+b.body+"</div>");b.width&&this.setSize(b.width,"auto");this.autoShow!==false&&this.show();b.handler&&K.App(["core/panel/AsyncDialog",
b.handler]).define(function(f){return f("core/panel/AsyncDialog").handlerFactory(f(b.handler),e,b.metaData)})}},this));a.send();return this}});return d});

define("core/async/Request",["jQuery"],function(i){var h=i("jQuery"),c=function(a){a&&this.setURI(a);this.method="GET";this.data={};this.xhr=null};K.mix(c,{load:function(a,b){var f=h(b).attr("data-ajax")=="request-post"?"POST":"GET",g=(new c(a)).setMethod(f).setHandler(function(d){d.handler&&K.App(["core/async/Request",d.handler]).define(function(e){e=K.create(e(d.handler));e.init(g,d);return e})}).setRelativeTo(b).send()}});K.mix(c.prototype,{setMethod:function(a){this.method=a;return this},getMethod:function(){return this.method},
setData:function(a){this.data=a;return this},getData:function(){return this.data},setURI:function(a){this.uri=a;return this},getURI:function(){return this.uri},setHandler:function(a){if(K.isFunction(a))this.handler=a;return this},getHandler:function(){return this.handler},setErrorHandler:function(a){this.errorHandler=a;return this},getErrorHandler:function(){return this.errorHandler},setRelativeTo:function(a){this.relativeTo=a;return this},getRelativeTo:function(){return this.relativeTo},send:function(){var a=
this;this.xhr=h.ajax({type:this.method,url:this.uri,data:this.data,dataType:"json"}).success(function(b){b.error?a.invokeErrorHandler(b):a.invokeResponseHandler(b)}).error(function(b){a.invokeErrorHandler(b)});return this},abort:function(){this.xhr&&this.xhr.abort();return this},invokeResponseHandler:function(a){"resource"in a?this.loadResource(a.resource,K.bind(function(){this.dispatchResponse(a)},this)):this.dispatchResponse(a)},invokeErrorHandler:function(a){this.dispatchErrorResponse(a)},loadResource:function(a,
b){"css"in a&&!K.isEmpty(a.css)?K.Resource.loadCSS(a.css,b):b();"js"in a&&!K.isEmpty(a.js)&&K.Resource.loadJS(a.js);var f=this;"onloads"in a&&setTimeout(function(){K.forEach(a.onloads,function(g){(new Function(g)).apply(f)})})},dispatchResponse:function(a){this.handler&&this.handler(a)},dispatchErrorResponse:function(a){this.errorHandler&&this.errorHandler(a)}});return c});
