
if(!this.JSON){this.JSON={};(function(){function f(n){return n<10?'0'+n:n;}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+
f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();};}
var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+
partial.join(',\n'+gap)+'\n'+
mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==='string'){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+
mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}
if(typeof JSON.parse!=='function'){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}
return reviver.call(holder,key,value);}
text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+
('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}
if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}
throw new SyntaxError('JSON.parse');};}}());}
(function(window,undefined){var SSO_SCHEMA="http://";var SSO_HOST='www.'+"kaixin001.com";var SSO_PATH="/interface/sso/";var SSO_API=SSO_SCHEMA+SSO_HOST+SSO_PATH;var $=window.jQuery;var crossDomainMessenger=(function(window){var $=window.jQuery;var supportPostMessage=("postMessage"in window);var getHash=function(target){return document.location.hash;};var interval_id,delay=100,last_hash="",inited=false;_callbacks=[];return{send:function(message,target,targetOrion){Log("send");message=JSON.stringify(message);if(supportPostMessage){target["postMessage"](message,targetOrion);}else{updateHash(target,message);}},initListener:function(target,targetOrion){Log("initListener");var callback=function(data){if(typeof(data)=="string"){var message=JSON.parse(data);}else{var message=data;}
Log(message);Log(this._callbacks);$.each(_callbacks,function(i,cb){cb(message);});};if(supportPostMessage){if("addEventListener"in window){window.addEventListener("message",function(e){callback(e.data);},false);}else{window.attachEvent("onmessage",function(e){callback(e.data);});}}else{interval_id&&clearInterval(interval_id);interval_id=null;interval_id=setInterval(function(){var hash=getHash(target);re=/^#\.+&/;if(hash!==last_hash){last_hash=hash;var data=Query.decode(decodeURIComponent(hash.replace(re,'')));if("message"in data){callback(data["message"]);}}},delay);}},receive:function(callback,sourceOrigin){_callbacks.push(callback);},stopListener:function(){interval_id&&clearInterval(interval_id);}};})(window);var simpleMessenger={_callbacks:[],send:function(message,target,targetOrigin){Log("send");message=JSON.stringify(message);target.SSOMessenger.accept(message);},receive:function(callback){this._callbacks.push(callback);},accept:function(message){Log("accept");var message=JSON.parse(message);$.each(this._callbacks,function(i,callback){callback(message);});},initListener:function(){},stopListener:function(){}};var Log=function(msg){if("console"in window&&"log"in window.console)
{console.log(msg);}};var subDomain=function(domain){return domain.replace(/[^\.]+\./,'');};var isSubDomain=function(from,to){var pos=to.indexOf(from);if(pos!=-1&&pos+from.length==to.length){return true;}
return false;};var Query={encode:function(params,sep,encode){sep=(sep===undefined)?'&':sep;encode=(encode===false)?function(s){return s;}:encodeURIComponent;var pairs=[];$.each(params,function(key,val){if(val!==null&&typeof val!="undefined"){pairs.push(encode(key)+'='+encode(val));}});pairs.sort();return pairs.join(sep);},decode:function(str){var
decode=decodeURIComponent,params={},parts=str.split('&'),i,pair;for(i=0;i<parts.length;i++){pair=parts[i].split('=',2);if(pair&&pair[0]){params[decode(pair[0])]=decode(pair[1]);}}
return params;}};var Encrypt={encode:function(password,key){return this.h(this.en(this.uen(password),key));},uen:function(str){str=(str+'').toString();return encodeURIComponent(str).replace(/!/g,'%21').replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29').replace(/\*/g,'%2A').replace(/%20/g,'+').replace(/~/g,'%7E');},en:function(password,key){if(password==""){return"";}
var v=this.sl(password,true);var k=this.sl(key,false);if(k.length<4){k.length=4;}
var n=v.length-1;var z=v[n],y=v[0],de=2654435769;var mx,e,p,q=Math.floor(6+52/(n+1)),sum=0;while(0<q--){sum=sum+de&0xffffffff;e=sum>>>2&3;for(p=0;p<n;p++){y=v[p+1];mx=(z>>>5^y<<2)+(y>>>3^z<<4)^(sum^y)+(k[p&3^e]^z);z=v[p]=v[p]+mx&0xffffffff;}
y=v[0];mx=(z>>>5^y<<2)+(y>>>3^z<<4)^(sum^y)+(k[p&3^e]^z);z=v[n]=v[n]+mx&0xffffffff;}
return this.bh(v);},sl:function(s,w){var len=s.length;var v=[];for(var i=0;i<len;i+=4){v[i>>2]=s.charCodeAt(i)|s.charCodeAt(i+1)<<8|s.charCodeAt(i+2)<<16|s.charCodeAt(i+3)<<24;}
if(w){v[v.length]=len;}
return v;},bh:function(ar){var charHex=new Array('0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f');var str="";var len=ar.length;for(var i=0,tmp=len<<2;i<tmp;i++)
{str+=charHex[((ar[i>>2]>>(((i&3)<<3)+4))&0xF)]+
charHex[((ar[i>>2]>>((i&3)<<3))&0xF)];}
return str;},h:function(msg){var K=[0x5a827999,0x6ed9eba1,0x8f1bbcdc,0xca62c1d6];msg+=String.fromCharCode(0x80);var l=msg.length/4+2;var N=Math.ceil(l/16);var M=new Array(N);for(var i=0;i<N;i++){M[i]=new Array(16);for(var j=0;j<16;j++){M[i][j]=(msg.charCodeAt(i*64+j*4)<<24)|(msg.charCodeAt(i*64+j*4+1)<<16)|(msg.charCodeAt(i*64+j*4+2)<<8)|(msg.charCodeAt(i*64+j*4+3));}}
M[N-1][14]=((msg.length-1)*8)/Math.pow(2,32);M[N-1][14]=Math.floor(M[N-1][14])
M[N-1][15]=((msg.length-1)*8)&0xffffffff;var H0=0x67452301;var H1=0xefcdab89;var H2=0x98badcfe;var H3=0x10325476;var H4=0xc3d2e1f0;var W=new Array(80);var a,b,c,d,e;for(var i=0;i<N;i++){for(var t=0;t<16;t++)W[t]=M[i][t];for(var t=16;t<80;t++)W[t]=this.rotl(W[t-3]^W[t-8]^W[t-14]^W[t-16],1);a=H0;b=H1;c=H2;d=H3;e=H4;for(var t=0;t<80;t++){var s=Math.floor(t/20);var T=(this.rotl(a,5)+this.f(s,b,c,d)+e+K[s]+W[t])&0xffffffff;e=d;d=c;c=this.rotl(b,30);b=a;a=T;}
H0=(H0+a)&0xffffffff;H1=(H1+b)&0xffffffff;H2=(H2+c)&0xffffffff;H3=(H3+d)&0xffffffff;H4=(H4+e)&0xffffffff;}
return this.tohs(H0)+this.tohs(H1)+this.tohs(H2)+this.tohs(H3)+this.tohs(H4);},tohs:function(str){var s="",v;for(var i=7;i>=0;i--){v=(str>>>(i*4))&0xf;s+=v.toString(16);}
return s;},rotl:function(x,n){return(x<<n)|(x>>>(32-n));},f:function(s,x,y,z){switch(s){case 0:return(x&y)^(~x&z);case 1:return x^y^z;case 2:return(x&y)^(x&z)^(y&z);case 3:return x^y^z;}}};var Api={_token:'',_container:null,_iframe:null,_iframeId:'',_messenger:null,_encryptKey:'',_callbacks:{},init:function(token,containerId){this._token=token;this.container=$("#"+containerId);this._initMessenger();this.postInit();},postInit:function(){},_initMessenger:function(){var domain=document.domain;if(domain==SSO_HOST||subDomain(SSO_HOST)==subDomain(domain)){document.domain=subDomain(domain);this._messenger=simpleMessenger;Log("using: simpleMessenger");}else if(domain==subDomain(SSO_HOST)){document.domain=domain;this._messenger=simpleMessenger;Log("using: simpleMessenger");}else if(isSubDomain(subDomain(SSO_HOST),domain)){document.domain=subDomain(SSO_HOST);this._messenger=simpleMessenger;Log("using: simpleMessenger");}else{this._messenger=crossDomainMessenger;Log("using: crossDomainMessenger");}
window.SSOMessenger=this._messenger;this._messenger.receive($.proxy(this._onMessage,this));},_onMessage:function(message){Log("gotMessage: ");Log(message);this._messenger.stopListener();var eventName=message.method+":"+(message.succ?"success":"error");if(message.succ==0)
{if(this.parseError(message)===false)
{return false;}}
Log("will publish event: "+eventName);this._publish(eventName,message);this.onMessage(message);this._done();},_getIframe:function(){if(!this._iframe){this._iframe=$("<iframe></iframe>").hide().appendTo("body");this._iframeId="KxSso_iframe_"+Math.round(Math.random()*1000);this._iframe.attr("id",this._iframeId);}
return this._iframe;},_queue:function(api,params,callback){if(!this.__queue){this.__queue=[];}
this.__queue.push([api,params,callback]);},_query:function(api,params,callback){if(!this._onQuery){this._doQuery(api,params,callback);}else{this._queue(api,params,callback);}},_done:function(){this._onQuery=false;if(this.__queue&&this.__queue.length){var data=this.__queue.shift();this._doQuery(data[0],data[1],data[2]);}},_doQuery:function(api,params,callback){this._onQuery=true;var iframe=this._getIframe();params["token"]=this._token;params["_"]=Math.random();this._messenger.initListener(this._iframe[0],"*");iframe.attr("src",SSO_API+api+".php?"+Query.encode(params));if(callback){var have_response=false,_this=this;var timer=setTimeout(function(){if(!have_response){_this.unsubscribe(handle);_this._publish(api+":error",{});}
_this._done();},10000);var handle=this.subscribe(api+":change",function(response){have_response=true;callback(response);_this.unsubscribe(handle);clearTimeout(timer);});}},_publish:function(eventName,data){Log("publish: "+eventName);if(eventName in this._callbacks){var callbacks=this._callbacks[eventName];$.each(callbacks,function(i,callback){if(callback){callback(data);}});}},subscribe:function(eventName,callback){if(!(eventName in this._callbacks)){this._callbacks[eventName]=[];}
this._callbacks[eventName].push(callback);return[eventName,callback];},unsubscribe:function(handle){var eventName=handle[0];var callback=handle[1];if(eventName in this._callbacks){var _this=this;$.each(this._callbacks[eventName],function(i,cb){if(cb==callback){_this._callbacks[eventName][i]=null;return false;}});}}};if(typeof(Object.create)==="undefined"){var create=function(obj){function F(){};F.prototype=obj;return new F();};}else{var create=Object.create;}
var KxReg=create(Api);$.extend(KxReg,{onMessage:function(message){this._publish(message.method+":change",message);},_captchaType:'chn',parseError:function(message){var reason='';if("errno"in message){var errno=message.errno;switch(errno){case 300100:reason="accountRequired";break;case 300102:reason="accountWrong";break;case 300103:reason="accountTaken";break;case 300201:reason="captchaRequired";break;case 300202:reason="captchaWrong";break;case 300203:reason="captchaForbidden";break;case 300301:reason="passwordRequired";break;case 300302:reason="passwordTooShort";break;case 300401:reason="ipForbidden";break;case 200100:case 200102:case 200103:reason="appTokenWrong";break;case 200101:case 200104:reason="permissionDenied";break;default:reason='unknown';}}
message.error={reason:reason,errno:errno};return true;},init:function(token,containerId,callback){delete this.init;this.init(token,containerId);this.subscribe("reginit:success",function(response){callback();});},postInit:function(){Log("postInit");var _this=this;this.reginit();this.subscribe("reginit:success",function(response){_this._captchaType=response.captchaType;});},reginit:function(callback){Log("reginit");this._query("reginit",{},callback);},reg:function(params,callback){this._query("reg",params,callback);},regcheck:function(name,params,callback){params["check"]=name;this._query("regcheck",params,callback);},getCaptcha:function(random){return"http://"+SSO_HOST+"/interface/getcaptcha.php?keytype=ssoreg&key="+random;}});window.KxReg=KxReg;})(window);if(typeof(window.KxReg_asyncInit)=="function"){setTimeout(function(){window.KxReg_asyncInit();},0);}