
if(!this.JSON){this.JSON={};(function(){function f(n){return n<10?'0'+n:n;}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+
f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();};}
var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+
partial.join(',\n'+gap)+'\n'+
mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==='string'){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+
mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}
if(typeof JSON.parse!=='function'){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}
return reviver.call(holder,key,value);}
text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+
('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}
if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}
throw new SyntaxError('JSON.parse');};}}());}
(function(window,undefined){var $debug=false,$=window.jQuery,SSO_SCHEMA="http://",SSO_HOST='www.'+"kaixin001.com",SSO_PATH="/interface/sso/",SSO_API="",isHttpsEnabled;$j.getScript('https://security.kaixin001.com/interface/probe.php',function(){isHttpsEnabled=window.con_https_enable;if(isHttpsEnabled===true){SSO_API='https://security.kaixin001.com'+SSO_PATH;}else{SSO_API=SSO_SCHEMA+SSO_HOST+SSO_PATH;}});doInitialize();function doInitialize(){var crossDomainMessenger=(function(window){var $=window.jQuery;var supportPostMessage=("postMessage"in window);var getHash=function(target){return document.location.hash;};var interval_id,delay=100,last_hash="",inited=false;_callbacks=[];return{type:"CrossDomainMessenger",send:function(message,target,targetOrion){Log("send");message=JSON.stringify(message);if(supportPostMessage){target["postMessage"](message,targetOrion);}else{updateHash(target,message);}},initListener:function(target,targetOrion){Log("initListener");var callback=function(data){if(typeof(data)=="string"){var message=JSON.parse(data);}else{var message=data;}
$.each(_callbacks,function(i,cb){cb(message);});};if(supportPostMessage){Log("using postMessage");if("addEventListener"in window){window.addEventListener("message",function(e){callback(e.data);},false);}else{window.attachEvent("onmessage",function(e){callback(e.data);});}}else{Log("using udpateHash");interval_id&&clearInterval(interval_id);interval_id=null;Log("start interval");interval_id=setInterval(function(){var hash=getHash(target),re=/^.*?#/,data;if(hash!==last_hash){last_hash=hash;data=Query.decode(hash.replace(re,''));for(i in data){data[i]=decodeURIComponent(data[i]);}
if("message"in data){callback(data["message"]);}}},delay);}},receive:function(callback,sourceOrigin){_callbacks.push(callback);},stopListener:function(){Log("stop listener");interval_id&&clearInterval(interval_id);},accept:function(message){Log("accept");var message=JSON.parse(message);$.each(_callbacks,function(i,callback){callback(message);});}};})(window);var simpleMessenger={type:"SimpleMessenger",_callbacks:[],send:function(message,target,targetOrigin){Log("send");message=JSON.stringify(message);target.SSOMessenger.accept(message);},receive:function(callback){this._callbacks.push(callback);},accept:function(message){Log("accept");var message=JSON.parse(message);$.each(this._callbacks,function(i,callback){callback(message);});},initListener:function(){},stopListener:function(){}};var Log=function(msg){if("console"in window&&"log"in window.console)
{console.log("kxsso.js:"+msg);}};var subDomain=function(domain){return domain.replace(/[^\.]+\./,'');};var isSubDomain=function(from,to){var pos=to.indexOf(from);if(pos!=-1&&pos+from.length==to.length){return true;}
return false;};var Query={encode:function(params,sep,encode){sep=(sep===undefined)?'&':sep;encode=(encode===false)?function(s){return s;}:encodeURIComponent;var pairs=[];$.each(params,function(key,val){if(val!==null&&typeof val!="undefined"){pairs.push(encode(key)+'='+encode(val));}});pairs.sort();return pairs.join(sep);},decode:function(str){var
decode=decodeURIComponent,params={},parts=str.split('&'),i,pair;for(i=0;i<parts.length;i++){pair=parts[i].split('=',2);if(pair&&pair[0]){params[decode(pair[0])]=decode(pair[1]);}}
return params;}};var Api={_token:'',_container:null,_iframe:null,_div:null,_iframeId:'',_messenger:null,_encryptKey:'',_callbacks:{},init:function(token,containerId){this._token=token;this.container=$("#"+containerId);},postInit:function(){},_initMessenger:function(){var domain=document.domain;Log("domain:"+domain);Log("host:"+SSO_HOST);if(isHttpsEnabled){this._messenger=crossDomainMessenger;Log("using: https & crossDomainMessenger");}else{if(domain==SSO_HOST||subDomain(SSO_HOST)==subDomain(domain)){document.domain=subDomain(domain);this._messenger=simpleMessenger;Log("using: simpleMessenger");}else if(domain==subDomain(SSO_HOST)){document.domain=domain;this._messenger=simpleMessenger;Log("using: simpleMessenger");}else if(isSubDomain(subDomain(SSO_HOST),domain)){document.domain=subDomain(SSO_HOST);this._messenger=simpleMessenger;Log("using: simpleMessenger");}else{this._messenger=crossDomainMessenger;Log("using: crossDomainMessenger");}}
window.SSOMessenger=this._messenger;this._messenger.__FILE__="kxsso.js";this._messenger.simplified=false;this._messenger.receive($.proxy(this._onMessage,this));},_onMessage:function(message){Log("gotMessage: ");this._messenger.stopListener();var eventName=message.method+":"+(message.succ?"success":"error");if(message.succ==0)
{if(this.parseError(message)===false)
{}}
Log("will publish event: "+eventName);this._publish(eventName,message);this.onMessage(message);},_getIframe:function(){var id,div,iframe=this._iframe,form,me=this;if(this._div==null){div=this._div=$("<div>");id=this._iframeId="KxSso_iframe_"+Math.round(Math.random()*1000);div[0].innerHTML='<iframe style="display:none" name="'
+id+'" id="'+id+'"></iframe><form></form>';iframe=this._iframe=div.children().first();div.appendTo("body");form=div.find("form");form.attr("name","params");form.attr("method","POST");form.attr("target",this._iframeId);}
iframe.post=function(src,params){var form=me._div.find("form"),lazySubmit=false;form.children().remove();$.each(params,function(name,value){var input=$("<input type='hidden' class='.params'/>");input.attr("name",name);input.attr("value",value);form.append(input);});form.attr("action",src);if($.browser.msie&&$.browser.version==6){var iframeSrc=iframe.attr('src');if(iframeSrc.indexOf('blank.php')==-1){lazySubmit=true;iframe.bind('load',function(){form.submit();});iframe.attr('src','http://www'+Kx.Lib.Request.getDomain()+'/interface/blank.php');}}
if(!lazySubmit){form.submit();}};return this._iframe;},_query:function(api,params,callback){var iframe=this._getIframe();params["token"]=this._token;if(!$debug)params["_"]=Math.random();this._messenger.initListener(this._iframe[0],"*");var url=SSO_API;if(api==="logout"||typeof(isHttpsEnabled)==="undefined"){url=SSO_SCHEMA+SSO_HOST+SSO_PATH+api+".php";}else{url+=api+".php";}
iframe.post(url,params);if(callback){var have_response=false,_this=this;var handle=this.subscribe(api+":change",function(response){Log("have response,callback");have_response=true;callback(response);_this.unsubscribe(handle);});setTimeout(function(){if(!have_response){Log("no response,unsubscribe");_this.unsubscribe(handle);_this._publish(api+":error",{});}},2000);}},_publish:function(eventName,data){Log("publish: "+eventName);if(eventName in this._callbacks){var callbacks=this._callbacks[eventName];$.each(callbacks,function(i,callback){if(callback){callback(data);}});}},subscribe:function(eventName,callback){if(!(eventName in this._callbacks)){this._callbacks[eventName]=[];}
this._callbacks[eventName].push(callback);return[eventName,callback];},unsubscribe:function(handle){var eventName=handle[0];var callback=handle[1];if(eventName in this._callbacks){var _this=this;$.each(this._callbacks[eventName],function(i,cb){if(cb==callback){_this._callbacks[eventName][i]=null;return false;}});}}};if(typeof(Object.create)==="undefined"){var create=function(obj){function F(){};F.prototype=obj;return new F();};}else{var create=Object.create;}
var KxSso=create(Api);$.extend(KxSso,{onMessage:function(message){this._publish(message.method+":change",message);},parseError:function(message){if("encryptKey"in message){this._encryptKey=message.encryptKey;}
var reason='';if("errno"in message){var errno=message.errno;switch(errno){case 100100:reason='accountRequired';break;case 100101:reason='accountNotExists';break;case 100103:reason='accountDeleted';break;case 100104:reason='accountBanned';break;case 100201:reason='passwordRequired';break;case 100202:reason='passwordWrong';break;case 100203:reason='passwordWrong2';break;case 100301:reason='captchaRequired';break;case 100302:reason='captchaWrong';break;case 100400:case 100401:case 100402:case 100403:reason='encryptKeyWrong';break;case 100501:reason='ipAddressWrong';break;case 200100:case 200102:case 200103:reason="appTokenWrong";break;case 200101:case 200104:reason="permissionDenied";break;default:reason='unknown';}}
message.error={reason:reason,errno:errno};if(reason=='encryptKeyWrong'){if(this._currLoginData)
{var params=$.extend({},this._currLoginData);this.login(params,$.noop);this._currLoginData=null;return false;}}
return true;},getStatus:function(callback){this._initMessenger();this.postInit();this._query("login",{},callback);},login:function(params,callback){Log("login");this._initMessenger();this.postInit();this._currLoginData=params;var login_para=$.extend({},params);login_para.password=params.password;login_para["encryptVer"]=-1;this._query("login",login_para,callback);},logout:function(callback){this._initMessenger();this.postInit();this._query("logout",{},callback);},getCaptcha:function(random){return"http://"+SSO_HOST+"/interface/getcaptcha.php?keytype=ssologin&key="+random;}});window.KxSso=KxSso;}})(window);if(typeof(window.KxSso_asyncInit)=="function"){setTimeout(function(){window.KxSso_asyncInit();},0);}