(function(){function q(a,b,e){b=b.replace(/^on/i,"").toLowerCase();if(a.attachEvent)a.attachEvent("on"+b,function(j){e.call(a,j)});else a.addEventListener&&a.addEventListener(b,e,false)}function i(){this.id=this.createUUID()}function p(){this.clicks=[];this.news=[];this.tags={};this.getTracker()}var o={cookie_uid_name:"_uid",cookie_tuid_name:"_tuid",cookie_main_domain:".kaixin001.com",cookie_kx_domain:".kx001.com",cookie_tkx_domain:"t.kx001.com",cookie_cn_domain:".kaixin001.com.cn",rcv:"u.kaixin001.com.cn/log.gif",
rcv_error:"u.kaixin001.com.cn/error.gif",rcv_monitor:"u.kaixin001.com.cn/monitor.gif",log_load_sign:"kaixin_log_loaded",cookie_vid_name:"_vid",cookie_vid_expires:31536E8,_n:(new Date).getTime(),isSent:0,onloadready:0,domready:0,timer:0,scroll_height:0,maxInt:2147483647,_t:["br","ck","cl","fl","ja","ln","rnd","sc","su","uid","vid","ou_type","ou_id","ti"]},r=[],f=[],c=[],g=document,n=g.location,h=g.referrer,d=window,l=encodeURIComponent;i.prototype.valueOf=function(){return this.id};i.prototype.toString=
function(){return this.id};i.prototype.createUUID=function(){var a=new Date(1582,10,15,0,0,0,0),b=(new Date).getTime()-a.getTime();a=i.getIntegerBits(b,0,31);var e=i.getIntegerBits(b,32,47);b=i.getIntegerBits(b,48,59)+"1";var j=i.getIntegerBits(i.rand(4095),0,7),m=i.getIntegerBits(i.rand(4095),0,7),k=i.getIntegerBits(i.rand(8191),0,7)+i.getIntegerBits(i.rand(8191),8,15)+i.getIntegerBits(i.rand(8191),0,7)+i.getIntegerBits(i.rand(8191),8,15)+i.getIntegerBits(i.rand(8191),0,15);return a+e+b+j+m+k};i.getIntegerBits=
function(a,b,e){a=i.returnBase(a,16);var j=[],m="",k=0;for(k=0;k<a.length;k++)j.push(a.substring(k,k+1));for(k=Math.floor(b/4);k<=Math.floor(e/4);k++)m+=!j[k]||j[k]==""?"0":j[k];return m};i.returnBase=function(a,b){return a.toString(b).toUpperCase()};i.rand=function(a){return Math.floor(Math.random()*(a+1))};p.prototype={setCookie:function(a,b,e,j,m){var k=new Date;k.setTime(k.getTime()+m);g.cookie=a+"="+b+(!m?"":"; expires="+k.toGMTString())+"; domain="+e+(j?"; path="+j:"")},getCookie:function(a){if(a=
RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(g.cookie))return a[2]||"";return""},ie:function(){return/msie (\d+\.\d)/i.test(navigator.userAgent)},getSc:function(){this.tags.sc=d.screen.width+"x"+d.screen.height},getCl:function(){this.tags.cl=d.screen?d.screen.colorDepth+"-bit":""},getCk:function(){this.tags.ck=navigator.cookieEnabled?"1":"0"},getFl:function(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)this.tags.fl=parseInt(a.description.replace(/([a-zA-Z]|\s)+/,
"").replace(/(\s)+r/,"."),10)+".0"}else if(d.ActiveXObject){a=0;for(var b=10;b>=2;b--)try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+b)){a=b+".0";break}}catch(e){}this.tags.fl=parseInt(a,10)+".0"}},getJa:function(){this.tags.ja=navigator.javaEnabled()?"1":"0"},getLn:function(){var a=navigator;this.tags.ln=(a.systemLanguage?a.systemLanguage:a.browserLanguage?a.browserLanguage:a.language?a.language:a.userLanguage?a.userLanguage:"-").toLowerCase()},getSu:function(){this.tags.su=h},getBr:function(){var a=
decodeURIComponent(navigator.userAgent.toLowerCase()),b,e=(b=a.match(/msie ([\d.]+)/))?e="ie"+b[1]:(b=a.match(/firefox\/([\d.]+)/))?e="firefox"+b[1]:(b=a.match(/chrome\/([\d.]+)/))?e="chrome"+b[1]:(b=a.match(/opera.([\d.]+)/))?e="opera"+b[1]:(b=a.match(/version\/([\d.]+).*safari/))?e="safari"+b[1]:(b=a.match(/maxthon\/([\d.]+)/))?e="maxthon"+b[1]:a.match(/gecko/)?e="gecko":"";this.tags.br=e?e.split(".")[0]:a},getUid:function(){var a=window.location.hostname;if(a){var b=a.indexOf("t.kx001.com")>=0?
this.getCookie(this.cookie_tuid_name):this.getCookie(this.cookie_uid_name);if(b=="")if(a.indexOf("kx001.com")>=0){a=this.getCookie("_user");if(a!="")b=a.split("_")[1]}this.tags.uid=b}},getVid:function(){var a=this.getCookie(this.cookie_vid_name);if(a==""){a=(new i).id;var b=window.location.hostname;if(b){b=b.indexOf("t.kx001.com")>=0?this.cookie_tkx_domain:b.indexOf(".kx001.com")>=0?this.cookie_kx_domain:b.indexOf(".kaixin001.com.cn")>=0?this.cookie_cn_domain:this.cookie_main_domain;this.setCookie(this.cookie_vid_name,
a,b,"/",this.cookie_vid_expires)}}this.tags.vid=a},getRnd:function(){this.tags.rnd=Math.round(Math.random()*o.maxInt)},getOuinfo:function(){try{if(typeof g_ouinfo!="undefined"&&g_ouinfo!=""){var a=$j.parseJSON(g_ouinfo);for(var b in a)if(a.hasOwnProperty(b))this.tags[b]=a[b]}}catch(e){}},getTi:function(){try{if(typeof g_st_time!="undefined"&&g_st_time!=""){var a=(new Date).getTime()-g_st_time;if(a<3E5)this.tags.ti=a}}catch(b){}},serialize:function(a){for(var b=[],e=o._t,j=0,m=e.length;j<m;j++){var k=
e[j];k=a[k]?k+"="+l(a[k]):k+"=";b.push(k)}return b.join("&")},getParameter:function(){this.getVid();this.getUid();this.getBr();this.getSu();this.getLn();this.getJa();this.getFl();this.getCk();this.getCl();this.getSc();this.getRnd();this.getOuinfo();this.getTi()},protocol:function(){return n.protocol=="https:"?"https://":"http://"},postData:function(){this.getParameter();var a=new Image(1,1);a.onload=function(){o.isSent=1};a.src=this.protocol()+this.rcv+"?"+this.serialize(this.tags)},postMonitorHandler:function(a){var b=
this;return function(){var e=new Image(1,1),j="";e.onload=function(){o.isSent=1};if(window.document.URL==a){j=Number(new Date);var m;try{m=K.Performance.timing.domContentLoadedEventStart-g_st_time}catch(k){m=b.domready-g_st_time}j="height="+window.document.body.scrollHeight+"&scroll="+b.scroll_height+"&domready="+m+"&onloadready="+(b.onloadready-g_st_time)+"&staytime="+(j-g_st_time)+"&click="+b.clicks.join(",")+"&screen="+b.tags.sc+"&uid="+b.tags.uid+"&news="+r.join(",")+"&right="+f.join(",")+"&rnd="+
b.tags.rnd}if(j!=="")j+="&";j+=K.Perf.getMarks();if(c.length>0)j+="&top="+c.join(",")+"&rnd="+b.tags.rnd;e.src=b.protocol()+b.rcv_monitor+"?"+j}},monitorScroll:function(){var a=this;return function(b){var e;if(b&&b.pageYOffset)e=b.pageYOffset;else if(document.documentElement&&document.documentElement.scrollTop)e=document.documentElement.scrollTop;else if(document.body)e=document.body.scrollTop;if(e>a.scroll_height)a.scroll_height=e}},recordDomReady:function(a){var b=this;return function(){if(a)try{document.body.doScroll("left");
b.domready=Number(new Date);clearInterval(b.timer)}catch(e){}else b.domready=Number(new Date)}},recordOnloadReady:function(){var a=this;return function(){a.onloadready=Number(new Date);K.Perf.markTime("wpo_onload")}},trackClick:function(){var a=this;return function(b){b=b||d.event;var e;if(a.ie()){var j=Math.max(g.documentElement.scrollTop,g.body.scrollTop);e=b.clientX+Math.max(g.documentElement.scrollLeft,g.body.scrollLeft);b=b.clientY+j}else{e=b.pageX;b=b.pageY}a.clicks.push(e+"|"+b)}},getTracker:function(){for(var a in o)if(a.indexOf("_")!==
0)this[a]=o[a];if(typeof window[this.log_load_sign]=="undefined"){window[this.log_load_sign]=true;try{this.postData()}catch(b){var e=[];e.push("hostname="+n.hostname);e.push("message="+l(b.message));e.push("name="+l(b.name));a=new Image(1,1);a.src=this.protocol()+this.rcv_error+"?"+e.join("&")}}a=this.tags.uid;e="http://www.kaixin001.com/home/?uid="+a;if(a&&a%100==71){q(d,"load",this.recordOnloadReady());q(d,"unload",this.postMonitorHandler(e));try{$j("#head .h1 a").click(function(){c.push("top_img_home")});
$j("#index_dropdown li.t_title").eq(0).click(function(){c.push("top_home")});$j("#index_dropdown li.t_title").eq(1).click(function(){c.push("top_friend")});$j("#index_dropdown li.t_title").eq(2).click(function(){c.push("top_app")});$j("#index_dropdown li.t_title").eq(3).click(function(){c.push("top_msg")});$j("#head1_kxt1").click(function(){c.push("top_service")});$j("#head1_kxt1 .i_serv5").click(function(){c.push("top_service_haibei")});$j("#head1_kxt1 .i_serv2").click(function(){c.push("top_service_teambuy")});
$j("#head1_kxt1 .i_serv4").click(function(){c.push("top_service_lite")});$j("#head2_kxt1").click(function(){c.push("top_zhaoren")});$j("#id_common_account").click(function(){c.push("top_account")});$j("#head a[href='/login/logout.php']").click(function(){c.push("top_logout")});$j("#appMenu .app_photo").click(function(){c.push("left_photo")});$j("#appMenu .app_diary").click(function(){c.push("left_diary")});$j("#appMenu .app_records").click(function(){c.push("left_records")});$j("#appMenu .app_repaste").click(function(){c.push("left_repaste")});
$j("#appMenu .app_gift").click(function(){c.push("left_gift")});$j("#appMenu .app_teambuy").click(function(){c.push("left_teambuy")})}catch(j){}if(window.document.URL==e){if(this.ie())this.timer=setInterval(this.recordDomReady(true),50);else window.addEventListener("DOMContentLoaded",this.recordDomReady(false),false);q(d,"scroll",this.monitorScroll());q(g,"mouseup",this.trackClick());try{$j("#divnews .gw1 a").click(function(){var k=$j(this).parents("div.gw1").find(">div.gw14").attr("class").split(" ")[2].split("_")[1];
r.push(k)});$j("#Feed_Navigation li[id], #newsdivhead li[id], #newsdivhead2 li[id], #recordsnewsdivhead li[id]").click(function(){r.push($j(this).attr("id"))});$j("#Feed_Navigation #newsMoreList a[data-jsaction]").click(function(){r.push("tab2_"+$j(this).attr("data-jsaction"))});$j("#eleSlideBox_visit a").click(function(){f.push("right_visit")});$j("#eleSlidePrev_visit").click(function(){f.push("right_visit_prev")});$j("#eleSlideNext_visit").click(function(){f.push("right_visit_next")});$j("#homeflist a").click(function(){f.push("right_friend")});
$j("#searchuser").click(function(){f.push("rightuser_search")});$j("#allfriendlistdiv a").click(function(){f.push("right_friend_all")});setTimeout(function(){$j("#calendar_box a").click(function(){f.push("right_calendar")});$j("#rollBox_1 a").click(function(){f.push("right_hot")});$j("#rollSlidePrev_1").click(function(){f.push("right_hot_prev")});$j("#rollSlideNext_1").click(function(){f.push("right_hot_next")});$j("#rollBox_2 a").click(function(){f.push("right_star")});$j("#rollSlidePrev_2").click(function(){f.push("right_star_prev")});
$j("#rollSlideNext_2").click(function(){f.push("right_star_next")});$j("#rollBox_3 a").click(function(){f.push("right_app")});$j("#rollSlidePrev_3").click(function(){f.push("right_app_prev")});$j("#rollSlideNext_3").click(function(){f.push("right_app_next")});$j("#rollBox_4 a").click(function(){f.push("right_act")});$j("#rollSlidePrev_4").click(function(){f.push("right_act_prev")});$j("#rollSlideNext_4").click(function(){f.push("right_act_next")})},2E3)}catch(m){}}}}};window.KX_TRACKER=new p})();
(function(){function q(c){if(window[i])return window[i][c];if(!p){for(var g=document.getElementsByTagName("script"),n=0,h=g.lenth;n<h;n++)if(g[n].getAttribute("marmot")=="true"){p=g[n].src;break}if(!p)p=g[g.length-1].src}if(c=p.match(RegExp(c+"=([^?#&=]*)","i")))return c[1];return null}var i="COMMON_LOG_CONF",p=null;if(window.KX_TRACKER.tags.vid){window[i]||(window[i]={pid:1E3,ratio:0.01});var o=q("ratio");if(o!==null){var r=window.KX_TRACKER.tags.vid.toString();if(parseInt(/(\w{2})$/.exec(r)[1],
16)>o*255)return}var f={_startTime:window.g_st_time,_pageID:q("pid"),_logData:[],_maxEvt:50,_preEvt:{t:"f",path:[]},_logUrl:("https:"==document.location.protocol?"https":" http")+"://u.kaixin001.com.cn/path.gif",_getPageWidth:function(){var c=document,g=c.body;return Math.max(c.documentElement.scrollWidth,g.scrollWidth,(c.compatMode=="BackCompat"?g:c.documentElement).clientWidth)},log:function(c){if(f._logData.length>=f._maxEvt){f.pushLog();f.pushLog=function(){}}else{c.t=="c"&&f._preEvt!==null&&
f._preEvt.t=="f"&&c.path.join("")==f._preEvt.path.join("")&&f._logData.pop();f._logData.push(c.x+"*"+c.y+"*"+c.path.join(""));f._preEvt=c}},stop:function(){f.pushLog=function(){}},pushLog:function(){var c=f._logData.join("!"),g=document.referrer;g.length>100&&g.split("?");c=["vid="+window.KX_TRACKER.tags.vid,"pid="+encodeURIComponent(this._pageID),"data="+c,"px="+window.screen.width+"*"+window.screen.height,"uid="+window.KX_TRACKER.tags.uid];this._startTime&&c.push("st="+(new Date-this._startTime));
document.createElement("img").src=f._logUrl+"?"+c.join("&")},inspect:function(){function c(h,d){if(h)return h;else if(d){if(d.document)return d.document.parentWindow.event;if(d.parentWindow)return d.parentWindow.event}return window.event||null}var g=function(){if(document.addEventListener)return function(h,d,l){h.addEventListener(d,l,true)};else if(document.attachEvent)return function(h,d,l){h.attachEvent("on"+d,l)}}();try{g(document,"mousedown",function(h){var d=c(h,this);h=f.getPath(d.target||d.srcElement);
var l;l=d.target||d.srcElement;var a=document;if(l)a=l.document||l.ownerDocument||(l.window||l.defaultView)&&l||document;l=a;d={x:"pageX"in d?d.pageX:d.clientX+(l.documentElement.scrollLeft||l.body.scrollLeft)-2,y:"pageY"in d?d.pageY:d.clientY+(l.documentElement.scrollTop||l.body.scrollTop)-2};f.log({x:d.x,y:d.y,path:h,t:"c"})});g(document,"focus",function(h){h=c(h,this);var d=h.target||h.srcElement;if(d.tagName){h=d.tagName.toUpperCase();if(h=="INPUT"||h=="TEXTAREA"||h=="BUTTON"||h=="SELECT"||h==
"OBJECT"||h=="EMBED"){h=f.getPath(d);d=d;var l=d.offsetTop,a=d.offsetLeft;for(d=d.offsetParent;d;){l+=d.offsetTop;a+=d.offsetLeft;d=d.offsetParent}d={x:l,y:a};f.log({x:d.x,y:d.y,path:h,t:"f"})}}});g(window,"beforeunload",function(){f.pushLog();f.pushLog=function(){}})}catch(n){}},getPath:function(c,g){g=g||[];var n;if(c==document.body||c.tagName&&c.tagName.toUpperCase()=="HTML")return g;if(c.getAttribute&&c.getAttribute("id")!=""&&c.getAttribute("id")){g.push(c.nodeName.toLowerCase()+"."+c.getAttribute("id"));
return g}if(c.parentNode&&c.parentNode.tagName.toUpperCase()!="BODY")g=f.getPath(c.parentNode,g);if(c.previousSibling){n=1;var h=c.previousSibling;do{h.nodeType==1&&h.nodeName==c.nodeName&&n++;h=h.previousSibling}while(h)}if(c.nodeType==1)g.push("~"+(n>1?n:1)+c.nodeName.toLowerCase());return g}};f.inspect()}})();
